### ISSUE TITLE
소모임디테일, 게시글뷰

### ISSUE THREAD

**Issue by mo-si-dev** [APP-iOS5th/FinalProject-Letports#106]
## 🗣 설명

- 소모임, 게시글 진입시  빈화면으로 떠있는문제 로딩관련 처리
- 소모임 이름이 길경우 화면을 벗어나는문제
- 소모임이름 영문으로 작성시 내비게이션 타이틀, 소모임제목에서 짤리는 문제
- 게시글 삭제시 추가팝업 추가(보류)
- 댓글이 제대로 안나오는 문제
- 다른사람의 게시글을 삭제, 수정이 가능한점
- 자유게시판 색상태그 추가
- 소모임 인원이 꽉찼을경우 가입하기버튼 비노출
- 가입취소, 탈퇴시 마스터에게 알림발송

## 📋 체크리스트

> 구현해야하는 이슈 체크리스트

- [x] 소모임, 게시글 진입시  빈화면으로 떠있는문제 로딩관련 처리
- [x] 소모임 이름이 길경우 화면을 벗어나는문제
- [x] 소모임이름 영문으로 작성시 내비게이션 타이틀, 소모임제목에서 짤리는 문제
- [x] 게시글 삭제시 추가팝업 추가(보류)
- [x] 댓글이 제대로 안나오는 문제
- [x] 다른사람의 게시글을 삭제, 수정이 가능한점
- [x] 자유게시판 색상태그 추가

**Comment by iOS-Ruel** [comment]
제가 진행중

**Comment by iOS-Ruel** [comment]
1. 소모임 이름이 길경우 화면을 벗어나는문제 - 트렐링 레이아웃 잡았지만 소모임제목 100글자는 너무 긴거 같음 20글자로 변경
2. 다른 사람 게시글일 경우 신고하기 sheet 처리
3. 해당 부분 높이 수정 처리
4. 자유게시판 색상태그 추가 -> @mo-si-dev 성근님이 추가하기로함
5. 댓글이 길어질경우 잘리는 문제 수정 
6. 게시글 삭제 얼럿 추가 및 삭제시 로딩 화면 추가
7. 소모임, 게시글 진입시 빈화면으로 떠있는문제 로딩관련 처리 -> 빈화면일 동안 로딩 뷰 추가
