### ISSUE TITLE
소모임 생성, 게시글생성

### ISSUE THREAD

**Issue by mo-si-dev** [APP-iOS5th/FinalProject-Letports#108]
## 🗣 설명

- 소모임 생성시 팀로고 보더 라운드, 라인 제거
- 소모임생성 게시글등록 버튼 사이즈 안맞는점 고정필요

## 📋 체크리스트

> 구현해야하는 이슈 체크리스트

- [x] 소모임 생성시 팀로고 보더 라운드, 라인 제거
- [x] 생성버튼 사이즈 안맞는점 고정필요

**Comment by iOS-Ruel** [comment]
@mo-si-dev 생성버튼 사이즈 안맞는게 뭐에요? 게시글 등록, 소모임 생성?

**Comment by mo-si-dev** [comment]
10번에 적혀있는거 그대로적었어요
