### ISSUE TITLE
Gathering Upload (모임 생성) 수정필요 ( 08 / 19 )

### ISSUE THREAD

**Issue by iOS-Ruel** [APP-iOS5th/FinalProject-Letports#18]
### 모임 생성시 현재 임의의 데이터로 모임 생성( 08/19 )
- 추후 선행 작업이 완료되면 데이터 변경 및 코드 수정 필요

## 📋 체크리스트

> 구현해야하는 이슈 체크리스트
- [x] 데이터 변경(모델)
- [x] 코드 수정

**Comment by SeongKookKIM** [comment]
확인했습니다.
