### ISSUE TITLE
소모임 디테일뷰

### ISSUE THREAD

**Issue by mo-si-dev** [APP-iOS5th/FinalProject-Letports#90]
## 🗣 설명
- 게시글 작성 + 버튼 있는곳에 있는 셀은 눌리지않는 버그
- +버튼이 눌렸을때 뒷배경도 어두워지면 좋을것같음 , 뒷배경을 누르면 + 버튼클릭 해제
- 소모임 신고하기 버튼 처리
- 소모임 가입시 마스터에게 가입 알림

## 📋 체크리스트

> 구현해야하는 이슈 체크리스트

- [x] 버튼과 같이 있는 셀도 눌리게 수정
- [x] 뒷배경 처리 
- [x] 소모임 신고하기 버튼 처리
- [x] 소모입 가입신청시 마스터에게 알림보내기

**Comment by iOS-Ruel** [comment]
뒷배경은 딤드를 넣지 않고 
postBtn 을 제외한 부분을 터치했을때 option View를 hidden 처리하는 방식으로 구현
- 뒷배경에 다른 버튼을 눌렀을때 동작하고, optionView는 hidden 처리됨
- 딤드를 넣기 위해서는 하단 탭바도 덮어 줘야하는데 현재 딤드 뷰로 하단 탭바를 덮게 되면 postBtn도 덮어짐. 
- 따라서 현재 상황상 해당 방법으로 처리함

**Comment by iOS-Ruel** [comment]
신고하기 버튼은 따로 로직은 없이
화면으로 보여졌을 때 신고가 되는 것처럼만 구현
