### ISSUE TITLE
게시글 디테일뷰

### ISSUE THREAD

**Issue by mo-si-dev** [APP-iOS5th/FinalProject-Letports#93]
## 🗣 설명
- 게시글 작성시간,  코멘트 작성시간  색상이 잘안보임
- 코멘트 빈값 작성버그, 첫댓글만 비어있을때 등록불가 이후엔  비어있어도 등록가능
- 게시글 신고 버튼 처리
- 게시글 삭제시 storage 사진삭제 처리

## 📋 체크리스트

> 구현해야하는 이슈 체크리스트

- [x] 게시글 작성시간,  코멘트 작성시간 색상 변경
- [x] 코멘트 등록 버그
- [x] 게시글삭제시 storage 사진도 삭제

**Comment by iOS-Ruel** [comment]
1. 게시글 작성시간, 코멘트 작성시간 색상 변경 -> 기본 LightGray으로 변경
2. 코멘트 등록 버그 -> 해당 이슈 수정 및 시뮬레이터에서 키보드 나왔을때 commentView와 간격이 있는 문제 수정
- 코멘트 등록시 등록 버튼을 누르면 키보드는 내려가지만 등록을 다시 눌러야 등록이 되는 문제 수정
